# Generated by Django 2.2.1 on 2019-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
